# Generated by Django 5.1.7 on 2025-03-28 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate_agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagency',
            name='representative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='representative_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestate',
            name='agency_real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_real_estate_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='photorealestate',
            name='additional_photo_real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_photo_RE_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='dataplot',
            name='real_estate_DP',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_DP_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='datahouse',
            name='real_estate_DH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_DH_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='dataapartment',
            name='real_estate_DA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_DA_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='agency_realtor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agency_realtor_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='reviewagency',
            name='review_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_agency_fk', to='real_estate_agency.realestateagency'),
        ),
        migrations.AddField(
            model_name='reviewagency',
            name='wrote_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrote_review_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackdeal',
            name='track_deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_deal_fk', to='real_estate_agency.deal'),
        ),
        migrations.AddField(
            model_name='trackdeal',
            name='who_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_track_fk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trackdeal',
            unique_together={('track_deal', 'who_track')},
        ),
    ]
