# Generated by Django 5.1.7 on 2025-04-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_agency', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewagency',
            unique_together=set(),
        ),
    ]
